---
title: "Data Manipulation"
output: github_document
---

```{r}
library(tidyverse)
```

Import FAS litters and pups. 

```{r}
litters_df = 
  read.csv("data/FAS_litters.csv")
litters_df = janitor::clean_names(litters_df)

pups_df = 
  read.csv("data/FAS_pups.csv")
pups_df = janitor::clean_names(pups_df)
```

## `select` function 

`select` is used to select columns! 

```{r}
#selecting only certian variables 
select(litters_df, group, litter_number, gd0_weight)

select(litters_df, group, gd0_weight:gd_of_birth)

select(litters_df, group, starts_with("pups"))

#removing columns with - 
select(litters_df, -litter_number)

select(litters_df, -starts_with("gd"))

#renaming column titles 
select(litters_df, group, litter_id = litter_number)

select(litters_df, group, litter_id = litter_number, everything())

#reordering and keeping everything else 
select(litters_df, gd0_weight, everything())
```


```{r}
#short-hand for renaming a column
rename(litters_df, litter_id = litter_number)

#moves a column up to the first column position 
relocate(litters_df, litter_number)
```

`select` vs. `pull`
```{r}
select(litters_df, group)
#select keeps the output in a datafram 
pull(litters_df, group)
#pull puts the output into a vector and follows tidyverse logic 
```


Learning Assessment: 
```{r}
select(pups_df, litter_number, sex, pd_ears)
```

## `filter`

You can get rid of rows using `filter()`

```{r}
#keeps only the data that satisfies the group == ""
filter(litters_df, group == "Con7")

#! means not, keeps everything BUT the thing after group ==
filter(litters_df, group != "Con7")

#using comparison 
filter(litters_df, gd0_weight > 20 )

filter(litters_df, group == "Con7"| group == "Con8")

filter(litters_df, group %in% c("Con7", "Con8"))
       
filter(litters_df, !(group == "Con7"))       
```

what about missing rows? 
```{r}
#get rid of anything that has missing values 
drop_na(litters_df)

#drop things that have missing values only in specified column 
drop_na(litters_df, gd0_weight)
```


## `mutate` 

this is used to add or change variables 

```{r}
#doing math between columns
mutate(litters_df, wt_gain = gd18_weight - gd0_weight)

#convert group variable to lower case 
mutate(litters_df, group = str_to_lower(group))

mutate(
  litters_df, 
  wt_gain = gd18_weight - gd0_weight,
  group = str_to_lower(group)
)
```

## `arrange`

```{r}
arrange(litters_df, gd0_weight)
arrange(litters_df, group, gd0_weight)
```

## pipes

```{r}
litters_df = 
  read_csv("data/FAS_litters.csv") |> 
  janitor::clean_names() |> 
  select(-starts_with("pups")) |> 
  mutate(
    group = str_to_lower(group), 
    wt_gain = gd18_weight - gd0_weight,
  ) |> 
    drop_na(wt_gain) |> 
    arrange(group, wt_gain)
```

