---
title: "Simple document"
output: github_document
---

```{r}
library(tidyverse)
library(readxl)
library(haven)
```


Let's import the `FAS_litters.csv` csv using a relative path. 

```{r, litter relative}
litters_df = 
  read_csv("data/FAS_litters.csv")

litters_df = 
  janitor::clean_names(litters_df)
```

Import the same dataset using an absolute path. 

```{r, litter absolute, eval = FALSE}
litters_df_abs  = 
  read_csv("~/Desktop/p8105/data_wrangling/data_wrangling_1/data/FAS_litters.csv")

litters_df_abs = 
  janitor::clean_names(litters_df_abs)
```

Now lets import the `FAS_pups.csv` dataset using a relative path. 

```{r, pups relative}
pups_df = 
  read_csv("data/FAS_pups.csv")

pups_df = 
  janitor::clean_names(pups_df)
```

## Looking at the data 

```{r}
litters_df

head(litters_df)

tail(litters_df)
```

You can use `view`
```{r, eval = FALSE}
view(litters_df)
```

Looking at a data summary: 

```{r}
str(litters_df)

skimr::skim(litters_df)
```

## Options in `read_*`

```{r}
litters_df = 
  read_csv(
    "data/FAS_litters.csv",
    skip = 10, col_names = FALSE
    )
```

Look at NA values. 

```{r}
litters_df = 
  read_csv(
    "data/FAS_litters.csv", 
    na = c("NA", 19)
      )
```


Column Types 

```{r}
litters_df = 
  read_csv(
    "data/FAS_litters.csv",
    col_types = 
      cols(
        `GD0 weight` = col_character() )
           )
```

## Other file types 

Import an xlsx file first. 

```{r}
mlb_df = 
  read_excel("data/mlb11.xlsx")
```

Import a SAS file. 

```{r}
pulse_df = 
  read_sas("data/public_pulse_data.sas7bdat")
```

